Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -16,10 +16,10 @@ jobs:
     runs-on: [self-hosted] 
 
     steps:      
-      - name: Cleanup Workspace
-        run: |
-          rm -rf ./* || true
-          rm -rf ./.??* || true
+      # - name: Cleanup Workspace
+      #   run: |
+      #     rm -rf ./* || true
+      #     rm -rf ./.??* || true
 
       # - name: Cleanup Runner
       #   run: |
@@ -27,23 +27,6 @@ jobs:
       #     docker rm $(docker ps -a -q)
       #     docker rmi $(docker images -a -q)
       #     docker volume rm $(docker volume ls -q)
-
-      - name: Install Docker
-        run: |
-          sudo apt-get update
-          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
-              apt-transport-https \
-              ca-certificates \
-              curl \
-              gnupg \
-              lsb-release
-          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
-          echo \
-            "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
-            $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
-          sudo apt-get update
-          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y docker-ce docker-ce-cli containerd.io
-
 
       - uses: actions/checkout@v2
       - name: Install Docker
